# generated by datamodel-codegen:
#   filename:  default_playlist.json
#   timestamp: 2022-12-10T16:32:57+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Snippet(BaseModel):
    type: str
    channel_id: str = Field(..., alias="channelId")
    position: int
    title: Optional[str] = None


class ContentDetails(BaseModel):
    playlists: Optional[List[str]] = None
    channels: Optional[List[str]] = None


class ChannelSectionsItem(BaseModel):
    kind: str
    etag: str
    id: str
    snippet: Snippet
    content_details: Optional[ContentDetails] = Field(None, alias="contentDetails")


class ChannelSections(BaseModel):
    kind: str
    etag: str
    items: List[ChannelSectionsItem]
