# generated by datamodel-codegen:
#   filename:  upload_list.json
#   timestamp: 2022-12-10T16:32:50+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Default(BaseModel):
    url: str
    width: int
    height: int


class Medium(BaseModel):
    url: str
    width: int
    height: int


class High(BaseModel):
    url: str
    width: int
    height: int


class Standard(BaseModel):
    url: str
    width: int
    height: int


class Maxres(BaseModel):
    url: str
    width: int
    height: int


class Thumbnails(BaseModel):
    default: Default
    medium: Medium
    high: High
    standard: Standard | None
    maxres: Maxres | None


class ResourceId(BaseModel):
    kind: str
    video_id: str = Field(..., alias="videoId")


class Snippet(BaseModel):
    published_at: str = Field(..., alias="publishedAt")
    channel_id: str = Field(..., alias="channelId")
    title: str
    description: str
    thumbnails: Thumbnails
    channel_title: str = Field(..., alias="channelTitle")
    playlist_id: str = Field(..., alias="playlistId")
    position: int
    resource_id: ResourceId = Field(..., alias="resourceId")
    video_owner_channel_title: str = Field(..., alias="videoOwnerChannelTitle")
    video_owner_channel_id: str = Field(..., alias="videoOwnerChannelId")


class ContentDetails(BaseModel):
    video_id: str = Field(..., alias="videoId")
    video_published_at: str = Field(..., alias="videoPublishedAt")


class Status(BaseModel):
    privacy_status: str = Field(..., alias="privacyStatus")


class PlaylistItemsItem(BaseModel):
    kind: str
    etag: str
    id: str
    snippet: Snippet
    content_details: ContentDetails = Field(..., alias="contentDetails")
    status: Status


class PageInfo(BaseModel):
    total_results: int = Field(..., alias="totalResults")
    results_per_page: int = Field(..., alias="resultsPerPage")


class PlaylistItems(BaseModel):
    kind: str
    etag: str
    items: List[PlaylistItemsItem]
    page_info: PageInfo = Field(..., alias="pageInfo")
